### ISSUE TITLE
Add v16 image

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud-ci/nodejs#38]
We just had the case in our main web repo that CI runs with owncloud-ci docker images on v14 whilst we're locally developing on v15 (which reaches its official EOL in a couple of weeks), causing some hickups and the need for re-introducing old features/polyfilling. Would be cool if we could switch to v16 as it's the new `current` version?

Feel free to close this issue if not applicable

**Comment by wkloucek** [comment]
Thanks notifying :+1:
