### ISSUE TITLE
Add chromedriver to v16 images

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud-ci/nodejs#53]
We'll begin to switch to v16 images in the `web` CI soon and would need the chromedriver from v14 to run playwright smoke tests without any additional setup

**Comment by wkloucek** [comment]
> We'll begin to switch to v16 images in the `web` CI soon and would need the chromedriver from v14 to run playwright smoke tests without any additional setup

That is already the case.
Did you already try it? If yes do you have a link to the failing pipeline? If not please close this issue.

**Comment by pascalwengerter** [comment]
Ah I see, sry for the noise
